const serverData = [
  {
    id: '1',
    name: 'CAS',
    type: 'folder',
    createdAt: new Date(),
    createdBy: 'main',
    modifiedAt: new Date(),
    modifiedBy: 'Megan Bowen',
    subFiles: [],
  },
  {
    id: '2',
    name: 'CoasterAndBargeLoading.xlsx',
    type: 'file',
    extension: 'xlsx',
    createdAt: new Date(),
    createdBy: 'main',
    modifiedAt: new Date(),
    modifiedBy: 'Administrator MOD',
  },
  {
    id: '3',
    name: 'RevenueByService.xlsx',
    type: 'file',
    extension: 'xlsx',
    createdAt: new Date(),
    createdBy: 'main',
    modifiedAt: new Date(),
    modifiedBy: 'Administrator MOD',
  },
  {
    id: '4',
    name: 'RevenueByService2016.xlsx',
    type: 'file',
    extension: 'xlsx',
    createdAt: new Date(),
    createdBy: 'main',
    modifiedAt: new Date(),
    modifiedBy: 'Administrator MOD',
  },
  {
    id: '5',
    name: 'RevenueByService2017.xlsx',
    type: 'file',
    extension: 'xlsx',
    createdAt: new Date(),
    createdBy: 'main',
    modifiedAt: new Date(),
    modifiedBy: 'Administrator MOD',
  },
];

export default serverData;
